import Head from "next/head";
import Link from "next/link";
import React from "react";
import LoginBtn from "./LoginBtn";

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="relative text-lg border border-gray-300">
        <ul className="flex justify-around w-1/3  items-center px-3 py-5  ">
          <li>
            <Link href="/">
              <a>Главная</a>
            </Link>
          </li>
          <li>
            <Link href="/todo">
              <a>задачи</a>
            </Link>
          </li>
          <li>
            <Link href="/">
              <LoginBtn />
            </Link>
          </li>
        </ul>
      </header>
      <main className="text-lg container mx-auto">{children}</main>
      <footer></footer>
    </>
  );
}
